"""empty message

Revision ID: 518fbb8eb31d
Revises: 
Create Date: 2018-11-02 21:55:55.170166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518fbb8eb31d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btxiaba',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('btxiaba_id', sa.String(length=255), server_default='', nullable=False),
    sa.Column('discuz_id', sa.String(length=255), server_default='', nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('thumb', sa.String(length=255), server_default='', nullable=True),
    sa.Column('imgs', sa.Text(), server_default='', nullable=True),
    sa.Column('direct', sa.String(length=255), server_default='', nullable=True),
    sa.Column('actor', sa.String(length=255), server_default='', nullable=True),
    sa.Column('type', sa.String(length=100), server_default='', nullable=True),
    sa.Column('area', sa.String(length=255), server_default='', nullable=True),
    sa.Column('language', sa.String(length=255), server_default='', nullable=True),
    sa.Column('year', sa.String(length=255), server_default='', nullable=True),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('download', sa.Text(), server_default='', nullable=True),
    sa.Column('created_time', sa.String(length=255), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('btxiaba')
    # ### end Alembic commands ###
